
services:

  db:
    image: postgres
    restart: always
    volumes: 
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/tasks_db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8081:8080"

volumes:
  pg_data:
